apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-canary
  namespace: aladin
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
      version: v2
  template:
    metadata:
      labels:
        app: my-app
        version: v2
    spec:
      containers:
      - name: my-app-container
        image: nginx:alpine

