apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: aladin
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-app
      version: v1
  template:
    metadata:
      labels:
        app: my-app
        version: v1
    spec:
      containers:
      - name: my-app-container
        image: nginx:alpine

