apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-07-24T21:21:12Z"
  generation: 1
  labels:
    app: my-webapp
  name: my-webapp
  namespace: default
  resourceVersion: "448456"
  uid: 3816ec65-2446-479b-ae65-419ee18784e3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-webapp
    spec:
      containers:
      - image: ngnix
        imagePullPolicy: Always
        name: ngnix
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
